apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: oa2p4f0bx-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oa2p4f0bx-python 
  name: oa2p4f0bx-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: oa2p4f0bx-python
    weight: 100 
